export const portfolio_works = [
  {
    id: 1,
    title: 'Invert 3D studio',
    image: '/images/works/work_invert.jpg',
    url: 'https://invert.studio',
    type: 'React, Next.js, Strapi.io, Docker, Tailwind.css, Figma prototype',
    text: 'Services for 3D visualization of architectural objects and objects, the creation of video clips based on 3D technology. We have a strong technical base and extensive experience, so we can offer a competitive product.',
  },
  {
    id: 2,
    title: 'MTNH - Architecture',
    image: '/images/works/work_mtnh.jpg',
    url: 'https://mtnh.ru/',
    type: 'Wordpress, Elementor plugin',
    text: 'Conceptual projects with original development in North Karelia region.',
  },
  {
    id: 3,
    title: 'Natmatch.com - Application',
    image: '/images/works/work_natmatch.jpg',
    url: 'https://natmatch.com',
    type: 'Next.js, Chakra-ui.com, SCSS, Figma prototype',
    text: 'Modern refactoring of The NMS Match Platform which is a modular, customizable, online system with tools to facilitate the full selection process for all stakeholders.',
  },
  {
    id: 4,
    title: 'Cental republic dispancery',
    image: '/images/works/work_crb.jpg',
    url: 'https://crb.onego.ru',
    type: 'Wordpress, SCSS, jQuery',
    text: 'The republican hospital website was redesigned with the transfer of all files and documents and designing new Figma original template.',
  },
  {
    id: 5,
    title: 'Asystems',
    image: '/images/works/work_asystems.jpg',
    url: 'https://a-systems.ru.com/',
    type: 'Drupal 10, PHP, SCSS',
    text: 'The company implements and develops secure information systems based on its own technological solutions and those of its partners.',
  },
  {
    id: 6,
    title: 'Italian Ceramics',
    image: '/images/works/work_ceramics.jpg',
    url: 'https://ceramicakarelia.com',
    type: 'Prestashop, jQuery, CSS, BEM, SCSS',
    text: 'The client asked to make an online store, choose a suitable content management system with the ability to order goods. It was necessary to parse goods from other sites and upload them to the database.',
  },
  {
    id: 7,
    title: 'ICSK website',
    image: '/images/works/work_icsk.jpg',
    url: 'https://icsk.ru',
    type: 'Drupal 7, Html, Css',
    text: 'The site of a large building Architecture design company, they needed to show all their built buildings, as well as reflect all the services offered.',
  },
  //   {
  //     id: 5,
  //     title: 'Concut website',
  //     image: '/images/works/works_concut.jpg',
  //     url: 'https://concut.ru',
  //     type: 'Drupal, CSS, SCSS',
  //     text: 'Customer provides hole drilling service. The site was made using BEM technology from a layout from Figma. Next, the layout was added to templates on Drupal 7. Multiple animations were made for design blocks on css 3.0.',
  //   },
];

